### ISSUE TITLE
Payback does not update

### ISSUE THREAD

**Issue by Cocovich** [Saluki/Barmate#19]
In a sale transaction, the payback value doesn't update at all (it stays at 0€), no matter what paid amount is entered.

**Comment by Saluki** [comment]
On which browser does the problem occurred? Does the development console shows any JS errors?

I tested it out on Firefox and Chrome and could unfortunately not find the bug back. Guess the problem is something similar to #9 where some incompatible JavaScript function was used.

**Comment by Cocovich** [comment]
You're right indeed ! The same JS error happens when I push any of the keypad button.
`TypeError: undefined is not a function (evaluating 'Number.parseFloat(this.sum)')`

**Comment by Saluki** [comment]
Could you copy/paste the JS line where it currently goes wrong? Or give the number if it isn't possible?

Just to make some research on the compatibility between browsers of the JS function...

**Comment by Cocovich** [comment]
It refers to the `updateRest` function of paymentView.js

**Comment by Cocovich** [comment]
Number.parseFloat() is [not supported](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Number/parseFloat#Compatibilit.C3.A9_des_navigateurs) by Safari but global method parseFloat() is.
