### ISSUE TITLE
Incorrect sale date

### ISSUE THREAD

**Issue by Cocovich** [Saluki/Barmate#20]
In current snapshot data, every sale date is said to have been made on 31 May 2015 15:25.

**Comment by Cocovich** [comment]
However, the value in DB is correct...

**Comment by Saluki** [comment]
In the "snapshot data" panel? The values are also correct in the database records on my system. Unfortunately, I could not find this bug back because the date property is displayed correctly:

![screenshot from 2015-06-13 17 59 23](https://cloud.githubusercontent.com/assets/2684557/8144999/28946f3a-11f6-11e5-8578-c535539b063c.png)

I will try a different approach to see if something changes...

**Comment by Cocovich** [comment]
I tried to debug it and I found that the time attribute, while correct in DB, is already wrong in the foreach loop of the CashController.
The weird value is caused by the fact that the first sale retrieved is of that date, so the date is unchanged rather than wrong...

**Comment by Saluki** [comment]
Nice you found it...

If, you've found the problem and you're currently on it, you can submit a patch commit if you want...

Thanks a lot for having found that bug :+1:

**Comment by Cocovich** [comment]
I don't know where the problem comes from.
![capture d ecran 2015-06-13 a 22 01 48](https://cloud.githubusercontent.com/assets/9592272/8145799/dabe070e-1217-11e5-9850-20285265a867.png)
It can't be the repository, so what ?

**Comment by Cocovich** [comment]
I just found that the retrieved date is the `cash_snapshots`'s date (not the first sale of the snapshot as I said earlier).
![capture d ecran 2015-06-13 a 22 18 42](https://cloud.githubusercontent.com/assets/9592272/8145867/364ee870-121a-11e5-8250-7818f25ebe24.png)
I begin to think that Laravel takes the time of the snapshot for the time of every of its details.

**Comment by Cocovich** [comment]
Ok I fixed it, the column `time` of `cash_snapshots` somehow overlap `snapshot_details`'s one so I refactored the latter and the problem's resolved !

**Comment by Cocovich** [comment]
To reproduce it, just make several sales in the same snapshot, you should have the same date (in fact the snapshot's creation date) for each transaction of this snapshot.
