### ISSUE TITLE
Making a sale while no snapshot

### ISSUE THREAD

**Issue by Cocovich** [Saluki/Barmate#25]
What should happen then ?
Why not start the application with a snapshot ?

**Comment by Saluki** [comment]
You hit a point...

For client side in POS component, this has already be mentioned in issue #12 (not yet closed). The objective is to display an error message when something goes wrong server-side.

Like you said, could be a really good idea to start with some "Initial snapshot" when launching Barmate. At first sight, I would rather go for a "seeding" solution that inserts a new snapshot.
