### ISSUE TITLE
Free sale button enhancement

### ISSUE THREAD

**Issue by Cocovich** [Saluki/Barmate#26]
Maybe do a tinier button or put a confirmation dialog to avoid mistakes and bad jokes.
After all, free sales don't happen SO often...

**Comment by Saluki** [comment]
Agree...

Just made some tests and, aesthetically speaking, it would be better to implement a confirmation dialog (same used in stock component). It should not be too difficult to quickly implement that...

**Comment by Saluki** [comment]
Result: 
![screenshot from 2015-06-15 19 24 29](https://cloud.githubusercontent.com/assets/2684557/8165889/5dca9f4a-1394-11e5-8378-c635c1590ee1.png)

**Comment by Cocovich** [comment]
Very well done !
