### ISSUE TITLE
Changing maintenance page

### ISSUE THREAD

**Issue by Saluki** [Saluki/Barmate#30]
When putting Barmate in maintenance mode using the **artisan down** command, the page displayed is views/errors/503.blade.php. Looks actually really nice and minimalistic, but has nothing common with the Barmate theme (dark blue/white). 

Perhaps spend some time to redesign the page?

**Comment by Cocovich** [comment]
Is it even an end-user functionality ?

**Comment by Saluki** [comment]
It's not a functionality, but rather a "design" issue...

**Comment by Saluki** [comment]
Maintenance page is now a minimalistic error page with Barmate's theme with a little CSS3 animation on the rocket:

![down](https://cloud.githubusercontent.com/assets/2684557/8416662/7ec98ae4-1ea7-11e5-8681-7014746f2b92.png)
