### ISSUE TITLE
Keypad freezes when paying

### ISSUE THREAD

**Issue by Cocovich** [Saluki/Barmate#8]
Just after installation and initialization, I could not type in the paid amount for a sale because the keypad would not respond. However, I can click Send, it doesn't make any sale (no stocks removal) but the ticket becomes empty...

**Comment by Saluki** [comment]
Fixed... The POS component used the JavaScript contains() function which is only supported by Firefox (and will apparently be changed).

http://stackoverflow.com/questions/19196337/string-contains-doesnt-exist-while-working-in-chrome

**Comment by Cocovich** [comment]
Well done :)
