### ISSUE TITLE
Paid value gets randomly 'undefined' when hitting clear button

### ISSUE THREAD

**Issue by Cocovich** [Saluki/Barmate#9]
Sometimes, when paying, the clear button on the keypad will set 'undefined' as paid value rather than removing last encoded digit.
![capture d ecran 2015-06-01 a 18 06 33](https://cloud.githubusercontent.com/assets/9592272/7917302/a1441a46-0889-11e5-9257-077599b59ece.png)

**Comment by Saluki** [comment]
Problem was here, JS view was looking for data-action attribute in child element.

```
<button class="btn-payment" data-action="R" style="background: #ffffff;">
    <i class="fa fa-mail-reply"></i>
</button>
```

Solved this by adding a data-action attribute to the child element...

```
<button class="btn-payment" data-action="R" style="background: #ffffff;">
    <i class="fa fa-mail-reply" data-action="R"></i>
</button>
```

Thanks for reporting... ^^
